// <auto-generated />
namespace sp16_p3_g8_WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class namechanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(namechanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201603302140582_name changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
