// <auto-generated />
namespace sp16_p3_g8WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class apimovieseeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(apimovieseeded));
        
        string IMigrationMetadata.Id
        {
            get { return "201604112331331_apimovieseeded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
